name: Compile

on: [push]

jobs:
  build-mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodule: recursive
    - name: Install boost
      run: brew install boost
    - name: CMake
      run: |
        mkdir -p build
        cd build && cmake ..; cd ..
    - name: Make
      run: make -C build
    - uses: actions/upload-artifact@master
      with:
        name: drt_mac
        path: bin/datareftool/mac.xpl

  build-lin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodule: recursive
    - name: CMake
      run: |
        env
        mkdir -p build
        cd build && cmake -DBoost_DIR=${BOOST_ROOT} -DBOOST_ROOT=${BOOST_ROOT} ..; cd ..
    - name: Make
      run: make -C build
    - uses: actions/upload-artifact@master
      with:
        name: drt_lin
        path: bin/datareftool/lin.xpl

  build-win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodule: recursive
    - name: CMake
      run: |
        mkdir -p build
        cd build && cmake -G "Visual Studio 16 2019" -A x64 ..; cd ..
    - name: Make
      run: msbuild.exe build/ALL_BUILD.vcxproj
    - uses: actions/upload-artifact@master
      with:
        name: drt_win
        path: bin/datareftool/win.xpl
