name: Compile

on: [push]

jobs:
  build-mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodule: recursive
    - name: Install boost
      run: brew install boost
    - name: CMake
      run: |
        mkdir -p build
        cd build && cmake -DCMAKE_BUILD_TYPE=Release ..; cd ..
    - name: Make
      run: make -C build
    - uses: actions/upload-artifact@master
      with:
        name: drt_mac
        path: bin/datareftool/mac.xpl
    - name: Dependencies
      run: otool -L bin/datareftool/mac.xpl

  build-lin:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y cmake libx11-dev libbz2-dev libglu1-mesa-dev g++-8
    - name: Install boost
      run: |
        export BOOST_DIR=~/boost_install
        wget -nv http://downloads.sourceforge.net/project/boost/boost/1.68.0/boost_1_68_0.tar.bz2
        tar --bzip2 -xf boost_1_68_0.tar.bz2
        cd boost_1_68_0/
        ./bootstrap.sh ${BOOST_BOOTSTRAP_FLAGS} --with-libraries=iostreams,filesystem,system,regex --prefix=${BOOST_DIR}
        ./b2 link=static threading=multi runtime-link=shared cxxflags=-fPIC
        ./b2 install --prefix=${BOOST_DIR}
    - uses: actions/checkout@v1
      with:
        submodule: recursive
    - name: CMake
      run: |
        mkdir -p build
        cd build && cmake -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=~/boost_install -DBOOST_INCLUDEDIR=~/boost_install/include ..; cd ..
    - name: Make
      run: make -C build
    - uses: actions/upload-artifact@master
      with:
        name: drt_lin
        path: bin/datareftool/lin.xpl
    - name: Dependencies
      run: ldd bin/datareftool/lin.xpl

  build-win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodule: recursive
    - name: CMake
      run: |
        mkdir -p build
        cd build && cmake -G "Visual Studio 16 2019" -A x64 ..; cd ..
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: MSBuild
      working-directory: build
      run: msbuild /p:Configuration=Release ALL_BUILD.vcxproj
      
    - uses: actions/upload-artifact@master
      with:
        name: drt_win
        path: bin/datareftool/Release/win.xpl
    - name: Dependencies
      run: >-
        "C:\\Program\ Files\ (x86)/Microsoft\ Visual\ Studio/2019/Enterprise/Common7/Tools/Bin/dumpbin.exe" /dependents bin/datareftool/Release/win.xpl
        
  build-zip:
   runs-on: ubuntu-latest
   needs: [build-mac, build-lin, build-win]
   steps:
     - uses: actions/checkout@v1
     - run: |
         mkdir -p binaries
         cp LICENSE binaries/
     - uses: actions/download-artifact@master
       with:
         name: drt_lin
         path: binaries/
     - uses: actions/download-artifact@master
       with:
         name: drt_mac
         path: binaries/
     - uses: actions/download-artifact@master
       with:
         name: drt_win
         path: binaries/
     - run: |
         ls -l binaries/
         mv binaries/ DataRefTool_`date +%Y_%m_%d`
         zip DataRefTool_build.zip DataRefTool_`date +%Y_%m_%d`/*
     - uses: actions/upload-artifact@master
       with:
         name: datareftool_build
         path: DataRefTool_build.zip
