name: Compile

on: [push]

jobs:
  build-mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodule: recursive
    - name: Install boost
      run: brew install boost
    - name: CMake
      run: |
        mkdir -p build
        cd build && cmake ..; cd ..
    - name: Make
      run: make -C build
    - uses: actions/upload-artifact@master
      with:
        name: drt_mac
        path: bin/datareftool/mac.xpl
    - name: Dependencies
      run: otool -L bin/datareftool/mac.xpl

  build-lin:
    runs-on: ubuntu-latest
    steps:
    - name: Install boost
      run: |
        sudo apt-get update -qq
        sudo apt-get install libboost-dev
    - uses: actions/checkout@v1
      with:
        submodule: recursive
    - name: CMake
      run: |
        ls $BOOST_ROOT
        ls $BOOST_ROOT/include
        mkdir -p build
        cd build && cmake ..; cd ..
    - name: Make
      run: make -C build
    - uses: actions/upload-artifact@master
      with:
        name: drt_lin
        path: bin/datareftool/lin.xpl
    - name: Dependencies
      run: ldd bin/datareftool/lin.xpl

  build-win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodule: recursive
    - name: CMake
      run: |
        mkdir -p build
        cd build && cmake -G "Visual Studio 16 2019" -A x64 ..; cd ..

    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: MSBuild
      working-directory: build
      run: msbuild /p:Configuration=Release ALL_BUILD.vcxproj
      
    - uses: actions/upload-artifact@master
      with:
        name: drt_win
        path: bin/datareftool/Release/win.xpl
    - name: Dependencies
      run: dumpbin /dependents bin/datareftool/Release/win.xpl
        
  build-zip:
   runs-on: ubuntu-latest
   needs: [build-mac, build-lin, build-win]
   steps:
     - uses: actions/checkout@v1
     - run: |
         export DATE=`date +%Y_%m_%d`
         export FOLDER=DataRefTool_${DATE}
         mkdir -p ${FOLDER}
         cp LICENSE ${FOLDER}/
     - uses: actions/download-artifact@master
       with:
         name: drt_lin
         path: ${FOLDER}/lin.xpl
     - uses: actions/download-artifact@master
       with:
         name: drt_mac
         path: ${FOLDER}/mac.xpl
     - uses: actions/download-artifact@master
       with:
         name: drt_win
         path: ${FOLDER}/win.xpl
     - run: zip ${FOLDER}.zip ${FOLDER}/*
     - uses: actions/upload-artifact@master
       with:
         name: drt_zip
         path: ${FOLDER}.zip
